// Auto-generated by convert_html.py – DO NOT EDIT manually.
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <pgmspace.h>

#ifdef __cplusplus
extern "C" {
#endif

// favicon.ico.c: 1150 bytes  (PROGMEM – flash, not RAM)
extern const uint8_t favicon_ico_data[] PROGMEM;
extern const size_t  favicon_ico_size;

#ifdef __cplusplus
}
#endif
