// Auto-generated by convert_html.py – DO NOT EDIT manually.
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <pgmspace.h>

#ifdef __cplusplus
extern "C" {
#endif

// index.html.c: 8676 bytes  (PROGMEM – flash, not RAM)
extern const uint8_t index_html_data[] PROGMEM;
extern const size_t  index_html_size;

#ifdef __cplusplus
}
#endif
