#!/usr/bin/env python3
"""
convert_html.py  –  embed web assets into C source for firmware.

Reads index.html and favicon.ico from the project root and writes:
    src/webui/index.html.c  /  src/webui/index.html.h
    src/webui/favicon.ico.c /  src/webui/favicon.ico.h

Run after every change to index.html or favicon.ico:
    python convert_html.py
"""

from __future__ import annotations

import os
import struct
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WEBUI_DIR  = os.path.join(SCRIPT_DIR, "src", "webui")


# ---------------------------------------------------------------------------
# C source generation
# ---------------------------------------------------------------------------

def bytes_to_c_files(
    data: bytes,
    *,
    var_name: str,
    c_filename: str,
    h_filename: str,
) -> tuple[str, str]:
    """
    Convert raw bytes to (c_source, c_header) strings.
    Data is placed in PROGMEM (flash); does not consume DRAM.
    On boards with BOARD_HAS_PSRAM the webserver copies it to PSRAM at startup.
    """
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    array_body = ",\n".join(rows)

    c_src = (
        "// Auto-generated by convert_html.py – DO NOT EDIT manually.\n"
        "// Regenerate: python convert_html.py\n"
        f'#include "{h_filename}"\n'
        "#include <stdint.h>\n"
        "#include <pgmspace.h>\n"
        "\n"
        f"const uint8_t {var_name}_data[] PROGMEM = {{\n"
        f"{array_body}\n"
        "};\n"
        "\n"
        f"const size_t {var_name}_size = sizeof({var_name}_data);\n"
    )

    c_hdr = (
        "// Auto-generated by convert_html.py – DO NOT EDIT manually.\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n"
        "#include <pgmspace.h>\n"
        "\n"
        "#ifdef __cplusplus\n"
        'extern "C" {\n'
        "#endif\n"
        "\n"
        f"// {c_filename}: {len(data)} bytes  (PROGMEM – flash, not RAM)\n"
        f"extern const uint8_t {var_name}_data[] PROGMEM;\n"
        f"extern const size_t  {var_name}_size;\n"
        "\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n"
    )
    return c_src, c_hdr


# ---------------------------------------------------------------------------
# Minimal favicon fallback  (16x16 teal, 32bpp ICO)
# ---------------------------------------------------------------------------

def make_minimal_favicon() -> bytes:
    """Build a 16x16 32bpp ICO file (teal #00897b) used when favicon.ico is absent."""
    W = H = 16
    pixel    = bytes([0x00, 0x89, 0x7b, 0xff])          # BGRA teal
    pixels   = pixel * (W * H)
    row_pad  = ((W + 31) // 32) * 4                      # AND-mask row size, DWORD-aligned
    and_mask = b"\x00" * (row_pad * H)

    bmp_hdr = struct.pack(
        "<IiiHHIIiiII",
        40,     # biSize
        W,      # biWidth
        H * 2,  # biHeight (pixels + AND mask)
        1,      # biPlanes
        32,     # biBitCount
        0, 0,   # biCompression, biSizeImage
        0, 0,   # biX/YPelsPerMeter
        0, 0,   # biClrUsed, biClrImportant
    )
    img_data  = bmp_hdr + pixels + and_mask
    dir_entry = struct.pack("<BBBBHHII", W, H, 0, 0, 1, 32, len(img_data), 22)
    icon_dir  = struct.pack("<HHH", 0, 1, 1)   # reserved, type=ICO, count=1
    return icon_dir + dir_entry + img_data


# ---------------------------------------------------------------------------
# Processing
# ---------------------------------------------------------------------------

def process_asset(
    src_path: str,
    var_name: str,
    c_filename: str,
    h_filename: str,
    fallback_fn=None,
) -> None:
    """Read asset file (or use fallback) and write generated C source + header."""
    if os.path.exists(src_path):
        with open(src_path, "rb") as fh:
            data = fh.read()
        print(f"  {os.path.basename(src_path)}: {len(data)} bytes")
    elif fallback_fn:
        data = fallback_fn()
        print(
            f"  {os.path.basename(src_path)}: not found – "
            f"using built-in placeholder ({len(data)} bytes)"
        )
    else:
        print(f"ERROR: required file not found: {src_path}", file=sys.stderr)
        sys.exit(1)

    c_src, c_hdr = bytes_to_c_files(
        data,
        var_name=var_name,
        c_filename=c_filename,
        h_filename=h_filename,
    )

    os.makedirs(WEBUI_DIR, exist_ok=True)
    out_c = os.path.join(WEBUI_DIR, c_filename)
    out_h = os.path.join(WEBUI_DIR, h_filename)

    with open(out_c, "w", newline="\n") as fh:
        fh.write(c_src)
    with open(out_h, "w", newline="\n") as fh:
        fh.write(c_hdr)

    print(f"    -> {os.path.relpath(out_c, SCRIPT_DIR)}")
    print(f"    -> {os.path.relpath(out_h, SCRIPT_DIR)}")


def main() -> None:
    print("convert_html.py: generating C web asset files...")
    process_asset(
        src_path   = os.path.join(SCRIPT_DIR, "index.html"),
        var_name   = "index_html",
        c_filename = "index.html.c",
        h_filename = "index.html.h",
    )
    process_asset(
        src_path    = os.path.join(SCRIPT_DIR, "favicon.ico"),
        var_name    = "favicon_ico",
        c_filename  = "favicon.ico.c",
        h_filename  = "favicon.ico.h",
        fallback_fn = make_minimal_favicon,
    )
    print("Done.")


if __name__ == "__main__":
    main()
